language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - asdf plugin-add svu ./
  - asdf list-all svu
  - asdf plugin-test svu ./ 'svu -v'
os:
  - osx
