name: Main workflow

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * 5"

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: svu --version
